[package]
name = "cloudflare_ddns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
ureq = { version = "2.12.1", features = ["json", "charset"] }
